version: "3"
services:
  docusaurus:
    env_file: .env
    #image: node:slim
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      # for linx or use windows docker desktop
      - ~/.ssh:/home/node/.ssh:cached
      - ..:/home/node/workspace:cached
