version: "3"
services:
  docusaurus:
    env_file: .env
    #image: node:slim
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ~/.ssh:/root/.ssh:cached
      - ..:/workspace:cached
